"""
Clean LeetCode topic/subtopic taxonomy.
Each subtopic belongs to exactly one topic.
"""

TAXONOMY: list[dict] = [
    {
        "topic": "Array",
        "subtopics": [
            {
                "name": "Prefix Sum",
                "description": "Precompute cumulative sums so any subarray sum can be answered in O(1). `prefix[i] = prefix[i-1] + arr[i]`, then `sum(i..j) = prefix[j] - prefix[i-1]`.",
                "when_to_use": "Subarray sum queries, range sum, counting subarrays with a given property.",
                "key_signals": "subarray sum equals k, continuous subarray, range query, cumulative count",
                "variants": "- **1D prefix sum**: standard cumulative sum\n- **2D prefix sum**: `prefix[i][j]` for submatrix sums\n- **Prefix XOR**: for subarray XOR queries",
                "implementation_keys": "1. Build prefix array: `prefix[0] = 0`, `prefix[i] = prefix[i-1] + arr[i-1]`\n2. Query: `sum(l, r) = prefix[r+1] - prefix[l]`\n3. Often combined with hash map for O(1) lookup of `prefix[j] - target`",
                "common_pitfalls": "Off-by-one in prefix indexing. For 'subarray sum = k', use hash map of prefix sums — don't iterate all pairs.",
            },
            {
                "name": "Difference Array",
                "description": "A difference array stores where values start changing and where those changes stop. For many range updates, you mark only the two boundaries instead of touching every element in the range. A final prefix-sum pass reconstructs the actual array because the running sum represents all active updates at each index.",
                "when_to_use": "Use when there are many range add/subtract operations and you only need the final array or final overlap counts after all operations. It turns repeated O(length of range) updates into O(1) marks plus one O(n) reconstruction pass.",
                "key_signals": "add value to a range, many interval updates, final array after operations, booking/counting overlaps, range increments before queries",
                "variants": "- **1D difference array**: mark `diff[l] += val` and `diff[r+1] -= val`, then prefix sum to recover values\n- **Sparse sweep line**: use a map of events when coordinates are huge; sort keys and accumulate active changes\n- **2D difference array**: mark four matrix corners with inclusion-exclusion for rectangle updates",
                "implementation_keys": "1. Create `diff = [0] * (n + 1)` so `r + 1` is safe.\n2. For each inclusive update `[l, r, val]`, do `diff[l] += val` and `diff[r + 1] -= val`; this records where the effect starts and stops.\n3. Walk left to right with `running += diff[i]`; `running` is the final value contributed by all active updates at index `i`.\n4. If coordinates are huge, store events in a dictionary instead of allocating an array.",
                "common_pitfalls": "- **Right boundary off by one**: subtract at `r + 1`, not `r`; the update should still affect index `r`.\n- **Inclusive vs exclusive ends**: decide whether intervals are `[l, r]` or `[start, end)` before marking the stop event.\n- **Returning raw diff**: the final answer comes from prefix summing `diff`, not from `diff` itself.",
            },
            {
                "name": "Two Pointers",
                "description": "Use two pointers moving inward or in the same direction to solve problems on sorted arrays or sequences in O(n).",
                "when_to_use": "Sorted arrays, pair finding, partitioning, removing duplicates.",
                "key_signals": "sorted array, pair sum, remove duplicates, reverse, partition, two ends",
                "variants": "- **Opposite direction**: start from both ends, shrink (e.g., 3Sum, Container With Most Water)\n- **Same direction**: fast/slow or read/write pointer (e.g., remove duplicates)\n- **Multiple arrays**: merge-style",
                "implementation_keys": "1. Sort if needed\n2. Initialize left=0, right=n-1 (or both at 0)\n3. Move based on comparison with target\n4. Skip duplicates when needed",
                "common_pitfalls": "Not handling duplicates in 3Sum. Moving wrong pointer. Forgetting to sort first.",
            },
            {
                "name": "Sliding Window",
                "description": "Maintain a window [left, right] over a contiguous subarray/substring, expanding right and shrinking left to satisfy constraints.",
                "when_to_use": "Finding longest/shortest contiguous subarray or substring satisfying a condition.",
                "key_signals": "longest / shortest subarray, at most k, distinct characters, contiguous, window",
                "variants": "- **Fixed size window**: slide window of size k\n- **Variable size window**: expand right, shrink left when constraint violated\n- **With hash map**: track character/element counts in window",
                "implementation_keys": "1. Expand right pointer one step at a time\n2. When window is invalid, shrink left until valid\n3. Track window state with counter/hash map\n4. Update answer at each valid state",
                "common_pitfalls": "Not shrinking left enough — must use `while` not `if`. Updating answer at wrong point (before vs after shrinking).",
            },
            {
                "name": "Sorting",
                "description": "Sort the input to enable greedy choices, binary search, or two-pointer techniques.",
                "when_to_use": "When ordering enables a simpler algorithm or greedy approach.",
                "key_signals": "order doesn't matter for answer, need pairs/groups, merge overlapping",
                "variants": "- **Custom sort**: sort by specific key (e.g., intervals by start)\n- **Counting sort**: O(n) when range is small\n- **Merge sort**: for inversion count or linked list sort",
                "implementation_keys": "1. Choose sort key carefully\n2. `sorted(arr, key=lambda x: ...)` for custom\n3. Stable sort matters when secondary ordering needed",
                "common_pitfalls": "Sorting when order matters in the original. Using O(n log n) sort when counting sort would be O(n).",
            },
        ],
    },
    {
        "topic": "Binary Search",
        "subtopics": [
            {
                "name": "Classic Search",
                "description": "Search for exact target in a sorted array in O(log n).",
                "when_to_use": "Sorted array, find exact value or insertion point.",
                "key_signals": "sorted, find target, search, insert position",
                "variants": "- **Exact match**: return index or -1\n- **Lower bound**: first element >= target\n- **Upper bound**: first element > target",
                "implementation_keys": "1. `lo, hi = 0, len(arr)-1`\n2. `while lo <= hi`: `mid = (lo+hi)//2`\n3. Adjust lo or hi based on comparison\n4. For lower/upper bound, use `lo < hi` and `lo = mid+1` or `hi = mid`",
                "common_pitfalls": "Off-by-one in lo/hi bounds. Infinite loop with wrong mid calculation. Using `<=` vs `<` incorrectly.",
            },
            {
                "name": "Search on Answer",
                "description": "Binary search on the answer space — guess an answer, check feasibility, and narrow the range.",
                "when_to_use": "Optimization problems where the answer is numeric and feasibility can be checked.",
                "key_signals": "minimize maximum, maximize minimum, smallest possible X, capacity/speed/days/distance",
                "variants": "- **Minimize maximum**: binary search + greedy feasibility check\n- **Maximize minimum**: binary search on the minimum value",
                "implementation_keys": "1. Define search range [lo, hi] on the answer\n2. Write `can_achieve(mid)` feasibility function\n3. Binary search: if feasible, try smaller/larger\n4. Return lo (or hi) depending on direction",
                "common_pitfalls": "Getting the feasibility check wrong. Off-by-one in final answer. Wrong direction (minimizing vs maximizing).",
            },
            {
                "name": "Rotated / Custom Search",
                "description": "Binary search on non-standard sorted structures: rotated arrays, matrices, or hidden monotonic functions.",
                "when_to_use": "Search space is sorted but with a twist — rotation, 2D structure, or implicit ordering.",
                "key_signals": "rotated sorted array, search in matrix, find minimum in rotated, peak element",
                "variants": "- **Rotated array**: find pivot, then search in correct half\n- **2D matrix search**: treat as 1D or binary search rows then columns\n- **Peak finding**: compare mid with neighbors",
                "implementation_keys": "1. Identify which half is sorted by comparing `arr[lo]`, `arr[mid]`, `arr[hi]`\n2. Check if target is in the sorted half\n3. For peak: if `arr[mid] < arr[mid+1]`, peak is right",
                "common_pitfalls": "Not handling duplicates in rotated search (worst case O(n)). Wrong comparison for identifying sorted half.",
            },
        ],
    },
    {
        "topic": "Hashing",
        "subtopics": [
            {
                "name": "Frequency Map",
                "description": "Use hash map to count occurrences, group elements, or find duplicates in O(n).",
                "when_to_use": "Counting, grouping, finding duplicates or complements.",
                "key_signals": "frequency, count, group, anagram, duplicate, most common",
                "variants": "- **Counter**: count frequencies\n- **Grouping**: group by key (e.g., sorted string for anagrams)\n- **Complement lookup**: find pairs summing to target",
                "implementation_keys": "1. `from collections import Counter` or `defaultdict(int)`\n2. One-pass for counting\n3. For Two Sum: store `{value: index}`, check if `target - num` exists",
                "common_pitfalls": "Using element as both key and lookup in same pass (Two Sum: check before inserting). Not handling 0-count entries.",
            },
            {
                "name": "Prefix Sum + Hash Map",
                "description": "Combine prefix sums with a hash map to find subarrays with specific sum properties in O(n).",
                "when_to_use": "Count subarrays with sum = k, or check if subarray sum divisible by k.",
                "key_signals": "subarray sum equals k, continuous subarray, number of subarrays with property",
                "variants": "- **Count subarrays**: `count += map[prefix - k]`\n- **Divisibility**: store `prefix % k` in map\n- **Binary subarrays**: prefix sum with 0/1 array",
                "implementation_keys": "1. Initialize `prefix_count = {0: 1}` (empty subarray)\n2. Running prefix sum\n3. At each step: `result += prefix_count.get(prefix - k, 0)`\n4. Then `prefix_count[prefix] += 1`",
                "common_pitfalls": "Forgetting to initialize `{0: 1}`. Updating the map BEFORE checking (causes counting same element). For mod: handle negative remainders.",
            },
            {
                "name": "Hash Set / Seen State",
                "description": "Use hash set to track visited states, detect cycles, or eliminate duplicates in O(1) per lookup.",
                "when_to_use": "Cycle detection, checking membership, longest consecutive sequence.",
                "key_signals": "cycle, visited, seen before, consecutive, unique",
                "variants": "- **Cycle detection**: track visited states (Happy Number)\n- **Consecutive sequence**: set lookup for `num-1` existence\n- **State hashing**: encode complex state as tuple for memoization",
                "implementation_keys": "1. `seen = set()`\n2. For cycle: compute next state, check if in seen\n3. For consecutive: only start counting from numbers where `num-1` not in set",
                "common_pitfalls": "Hashing mutable objects (use tuple, not list). For consecutive sequence: must skip non-start elements to stay O(n).",
            },
        ],
    },
    {
        "topic": "Stack",
        "subtopics": [
            {
                "name": "Normal Stack",
                "description": "LIFO structure for matching brackets, undo operations, and nested structures.",
                "when_to_use": "Matching pairs, nested structures, undo/redo, DFS simulation.",
                "key_signals": "parentheses, brackets, matching, nested, valid, undo",
                "variants": "- **Matching**: push open, pop on close\n- **Path simplification**: push directories, pop on `..`\n- **Min stack**: maintain parallel stack of minimums",
                "implementation_keys": "1. Push candidates onto stack\n2. Pop when match/condition found\n3. Check stack empty for valid state",
                "common_pitfalls": "Popping from empty stack. Not checking final stack state (leftover elements = invalid).",
            },
            {
                "name": "Monotonic Stack",
                "description": "Maintain a stack where elements are in strictly increasing or decreasing order to find next greater/smaller elements in O(n).",
                "when_to_use": "Finding next/previous greater or smaller element for each position.",
                "key_signals": "next greater element, previous smaller, largest rectangle, daily temperatures, stock span",
                "variants": "- **Decreasing stack**: for next greater element\n- **Increasing stack**: for next smaller element\n- **With index**: store indices to calculate distances",
                "implementation_keys": "1. Iterate array left to right\n2. While stack not empty AND current element > stack top: pop (found next greater for popped element)\n3. Push current element/index\n4. Elements remaining in stack have no next greater",
                "common_pitfalls": "Wrong monotonic direction (increasing vs decreasing). Not storing indices when distances needed. Off-by-one when computing widths (Largest Rectangle).",
            },
            {
                "name": "Parsing",
                "description": "Use stack for expression evaluation, nested formula parsing, or grammar-like string processing.",
                "when_to_use": "Calculator problems, nested brackets with operations, decode strings.",
                "key_signals": "calculator, expression, decode, nested formula, evaluate",
                "variants": "- **Basic calculator**: stack of (sign, partial_result)\n- **Decode string**: stack of (count, accumulated_string)\n- **Nested multiplication**: recursive or stack-based",
                "implementation_keys": "1. Push context (current result + operator) when opening bracket\n2. Pop and apply when closing bracket\n3. Handle operator precedence with two stacks or by processing `*` `/` immediately",
                "common_pitfalls": "Not handling negative numbers. Wrong precedence (must process `*` before `+`). Forgetting to process remaining operators at end.",
            },
        ],
    },
    {
        "topic": "Queue / Heap",
        "subtopics": [
            {
                "name": "BFS Queue",
                "description": "Use queue for breadth-first traversal — level-by-level exploration guaranteeing shortest path in unweighted graphs.",
                "when_to_use": "Shortest path in unweighted graph/grid, level-order traversal.",
                "key_signals": "shortest path, minimum steps, level by level, nearest, rotting oranges",
                "variants": "- **Standard BFS**: single source\n- **Multi-source BFS**: start from all sources simultaneously\n- **0-1 BFS**: deque for graphs with edge weights 0 or 1",
                "implementation_keys": "1. `queue = deque([start])`, `visited = {start}`\n2. Process level by level: `for _ in range(len(queue))`\n3. Add unvisited neighbors\n4. Distance = number of levels",
                "common_pitfalls": "Not marking visited BEFORE adding to queue (causes duplicates). Not handling multi-source correctly. Using DFS when BFS needed for shortest path.",
            },
            {
                "name": "Monotonic Queue",
                "description": "Deque maintaining monotonic order for sliding window max/min queries in O(n) total.",
                "when_to_use": "Sliding window maximum/minimum, shortest subarray with sum >= k.",
                "key_signals": "sliding window maximum, sliding window minimum, shortest subarray with sum at least k",
                "variants": "- **Decreasing deque**: for window max\n- **Increasing deque**: for window min",
                "implementation_keys": "1. `deque` stores indices\n2. When adding index i: pop from back while `arr[back] <= arr[i]` (for max)\n3. When window moves: pop from front if `front < left`\n4. Front of deque = current max/min",
                "common_pitfalls": "Popping from wrong end. Not removing expired indices from front. Comparing values but storing indices (or vice versa).",
            },
            {
                "name": "Priority Queue / Heap",
                "description": "Efficiently access smallest/largest element. Python's `heapq` is a min-heap.",
                "when_to_use": "Repeatedly needing the smallest/largest, top-k, merge k sorted, scheduling.",
                "key_signals": "top k, kth largest, merge k sorted, scheduling by earliest/latest, Dijkstra",
                "variants": "- **Min heap**: default `heapq` for smallest first\n- **Max heap**: negate values for largest first\n- **Lazy deletion**: mark deleted, skip when popped\n- **Two heaps**: median tracking",
                "implementation_keys": "1. `heapq.heappush(h, val)` and `heapq.heappop(h)`\n2. For max heap: push `-val`, negate on pop\n3. For k-th largest: maintain min-heap of size k\n4. For merge k: push `(val, list_idx, elem_idx)` tuples",
                "common_pitfalls": "Python heapq is min-heap only — forgetting to negate for max. Heap of tuples compares all elements — add tiebreaker. Lazy deletion without checking validity on pop.",
            },
        ],
    },
    {
        "topic": "String",
        "subtopics": [
            {
                "name": "String Sliding Window",
                "description": "Sliding window technique applied to strings — track character counts in window.",
                "when_to_use": "Find substrings with specific character properties.",
                "key_signals": "minimum window substring, permutation in string, longest repeating character replacement",
                "variants": "- **With counter map**: track needed vs have\n- **With fixed alphabet**: array of 26 for lowercase",
                "implementation_keys": "1. Use `Counter` for target string\n2. Expand right, track `have` count\n3. Shrink left when all characters satisfied\n4. Update minimum length",
                "common_pitfalls": "Not handling duplicate characters correctly. Off-by-one in window boundaries. Not updating `have` count when shrinking removes a needed character.",
            },
            {
                "name": "Trie",
                "description": "Tree structure where each node represents a character. Efficient for prefix operations over a dictionary of words.",
                "when_to_use": "Many words sharing prefixes, dictionary lookup, autocomplete, board + word list.",
                "key_signals": "prefix, word dictionary, autocomplete, word search, starts with",
                "variants": "- **Standard trie**: insert/search/startsWith\n- **Trie + DFS**: word search on grid\n- **Trie + backtracking**: prune search space using trie",
                "implementation_keys": "1. Node has `children = {}` dict and `is_end = False`\n2. Insert: walk/create nodes for each char, mark end\n3. Search: walk existing nodes, check `is_end`\n4. For Word Search II: build trie from words, DFS grid checking trie nodes",
                "common_pitfalls": "Not marking `is_end` for short words that are prefixes of longer ones. Memory: each node stores up to 26 children. For Word Search II: remove found words from trie to avoid duplicates.",
            },
            {
                "name": "KMP",
                "description": "Knuth-Morris-Pratt algorithm for efficient substring pattern matching in O(n+m) using a failure function.",
                "when_to_use": "Finding pattern in text, or leveraging prefix-suffix structure.",
                "key_signals": "pattern matching, shortest palindrome, repeated pattern",
                "variants": "- **Standard KMP**: pattern search\n- **Failure function only**: find longest prefix-suffix for palindrome/repeat problems",
                "implementation_keys": "1. Build failure/LPS array for pattern\n2. `lps[i]` = length of longest proper prefix of pattern[0..i] that is also a suffix\n3. On mismatch: jump to `lps[j-1]` instead of restarting",
                "common_pitfalls": "Building LPS array incorrectly — must handle the case where `pattern[i] != pattern[len]` by falling back to `lps[len-1]`.",
            },
            {
                "name": "Rolling Hash",
                "description": "Hash substrings in O(1) per slide using polynomial rolling hash for fast comparison.",
                "when_to_use": "Substring comparison, finding duplicate substrings, Rabin-Karp.",
                "key_signals": "repeated substring, duplicate substring, pattern matching with hash",
                "variants": "- **Rabin-Karp**: rolling hash for pattern search\n- **Double hash**: two different bases/mods to reduce collisions",
                "implementation_keys": "1. Hash = sum of `char * base^i` mod M\n2. To slide window: subtract leftmost char contribution, multiply by base, add new char\n3. On hash match: verify actual string (collision possible)",
                "common_pitfalls": "Hash collisions — always verify matches. Overflow with large base/mod. Precompute `base^k mod M` for efficiency.",
            },
            {
                "name": "String Parsing",
                "description": "Process strings character by character with stack or state machine for complex format handling.",
                "when_to_use": "Evaluate expressions, decode encoded strings, parse structured text.",
                "key_signals": "decode string, number of atoms, expression, nested brackets in string",
                "variants": "- **Stack-based**: push/pop for nested structures\n- **State machine**: track current state (number, letter, operator)",
                "implementation_keys": "1. Iterate chars, accumulate digits/letters\n2. On `[` or `(`: push current state to stack\n3. On `]` or `)`: pop and apply\n4. Handle multi-digit numbers",
                "common_pitfalls": "Multi-digit numbers (must accumulate). Nested brackets requiring recursive application. Not handling empty strings between delimiters.",
            },
        ],
    },
    {
        "topic": "Linked List",
        "subtopics": [
            {
                "name": "Fast Slow Pointers",
                "description": "Two pointers moving at different speeds to detect cycles, find middle, or check palindromes.",
                "when_to_use": "Cycle detection, finding middle node, palindrome check.",
                "key_signals": "cycle, middle, palindrome, intersection, linked list",
                "variants": "- **Cycle detection**: slow moves 1, fast moves 2; if they meet, cycle exists\n- **Find middle**: when fast reaches end, slow is at middle\n- **Find cycle start**: after meeting, reset one to head, both move 1 step",
                "implementation_keys": "1. `slow = fast = head`\n2. `while fast and fast.next`: `slow = slow.next`, `fast = fast.next.next`\n3. For cycle start: `slow = head`, then both move 1 until meeting",
                "common_pitfalls": "Null pointer when fast.next is None. Not resetting to find cycle start. Even vs odd length for middle (slow lands differently).",
            },
            {
                "name": "Reverse / Merge",
                "description": "Core linked list operations: reversing sublists and merging sorted lists.",
                "when_to_use": "Reverse linked list, merge k sorted lists, reorder list.",
                "key_signals": "reverse, merge, reorder, rotate, swap nodes",
                "variants": "- **Full reverse**: iterative or recursive\n- **Partial reverse**: reverse between positions l and r\n- **Merge two sorted**: compare and link\n- **Merge k sorted**: heap of k list heads",
                "implementation_keys": "1. Reverse: `prev = None; while curr: next = curr.next; curr.next = prev; prev = curr; curr = next`\n2. Merge: dummy head, compare and advance smaller\n3. Save `next` before modifying any pointer",
                "common_pitfalls": "Losing reference to next node before relinking. Not updating `prev` in partial reverse. Forgetting dummy node for merge.",
            },
            {
                "name": "Dummy Node",
                "description": "Use a dummy/sentinel head node to simplify edge cases when the head of the list might change.",
                "when_to_use": "When deleting head, building new list, or merging.",
                "key_signals": "remove head, build result list, partition list",
                "variants": "- **Single dummy**: `dummy.next = head`, return `dummy.next`\n- **Two dummies**: for partitioning into two lists",
                "implementation_keys": "1. `dummy = ListNode(0, head)`\n2. Work with `prev = dummy`\n3. Return `dummy.next`",
                "common_pitfalls": "Forgetting to return `dummy.next` instead of `head`. Not breaking the cycle when reconnecting partitioned lists.",
            },
        ],
    },
    {
        "topic": "Tree",
        "subtopics": [
            {
                "name": "DFS",
                "description": "Depth-first traversal of tree — preorder, inorder, postorder. Foundation for most tree problems.",
                "when_to_use": "Subtree information, height, path sum, validation, diameter.",
                "key_signals": "maximum depth, diameter, path sum, validate BST, subtree, ancestor",
                "variants": "- **Preorder**: process node, then children (top-down)\n- **Postorder**: process children, then node (bottom-up, most common)\n- **Inorder**: left, node, right (BST gives sorted order)",
                "implementation_keys": "1. Base case: `if not node: return default`\n2. Recurse left and right\n3. Combine results at current node\n4. Return value that parent needs",
                "common_pitfalls": "Not handling None nodes. Confusing what to return vs what to update globally. For diameter: return height but track diameter as side effect.",
            },
            {
                "name": "BFS",
                "description": "Level-order traversal using queue — process all nodes at depth d before depth d+1.",
                "when_to_use": "Level-by-level processing, right side view, zigzag, minimum depth.",
                "key_signals": "level order, right side view, zigzag, minimum depth, connect next pointers",
                "variants": "- **Standard BFS**: process level by level\n- **Right side view**: last node of each level\n- **Zigzag**: alternate direction per level",
                "implementation_keys": "1. `queue = deque([root])`\n2. `for _ in range(len(queue))`: process current level\n3. Add children to queue",
                "common_pitfalls": "Not capturing level size before processing (queue grows during iteration). Forgetting null check before adding children.",
            },
            {
                "name": "BST",
                "description": "Binary Search Tree property: left < node < right. Enables O(log n) search, insert, delete.",
                "when_to_use": "Sorted property needed, kth smallest, validation, range queries.",
                "key_signals": "kth smallest, validate BST, delete node, inorder successor, range sum",
                "variants": "- **Inorder traversal**: gives sorted sequence\n- **Search/Insert**: standard BST operations\n- **Delete**: handle 0, 1, 2 children cases",
                "implementation_keys": "1. Validate: pass `(low, high)` bounds, check `low < node.val < high`\n2. Kth smallest: inorder traversal with counter\n3. Delete: find inorder successor (smallest in right subtree), swap, delete",
                "common_pitfalls": "Validate BST: must pass bounds down, not just compare with parent (grandparent constraint). Delete: not handling the case where node has two children correctly.",
            },
            {
                "name": "LCA",
                "description": "Lowest Common Ancestor — find the deepest node that is ancestor of both given nodes.",
                "when_to_use": "Finding common ancestor, distance between nodes, path queries.",
                "key_signals": "lowest common ancestor, path between nodes, distance in tree",
                "variants": "- **Binary tree LCA**: recursive, check if p/q in left/right subtree\n- **BST LCA**: use BST property to choose direction\n- **With parent pointers**: two-pointer intersection technique",
                "implementation_keys": "1. If `node == p or node == q or node is None`: return node\n2. Recurse left and right\n3. If both non-null: current node is LCA\n4. Otherwise return the non-null side",
                "common_pitfalls": "Assuming both p and q exist in tree. For BST: not using the BST property (O(n) instead of O(h)).",
            },
            {
                "name": "Tree DP",
                "description": "Dynamic programming on tree where each node returns states computed from children.",
                "when_to_use": "When optimal solution depends on subtree choices — rob/not-rob, camera placement.",
                "key_signals": "binary tree cameras, house robber III, maximum path sum, tree coloring",
                "variants": "- **Two-state**: (include, exclude) for each node\n- **Multi-state**: (covered, has_camera, not_covered) for cameras\n- **Path DP**: max path sum through a node",
                "implementation_keys": "1. DFS returns tuple of states\n2. Combine children's states at each node\n3. For path sum: return `node.val + max(left, right, 0)` but track `left + node + right` globally",
                "common_pitfalls": "Confusing what to RETURN (for parent's computation) vs what to UPDATE globally. For path sum: the path through node uses both children but return value uses only one.",
            },
            {
                "name": "Serialization",
                "description": "Convert tree to string representation and reconstruct it — preorder or level-order with null markers.",
                "when_to_use": "Serialize/deserialize trees for storage or comparison.",
                "key_signals": "serialize, deserialize, encode tree, codec",
                "variants": "- **Preorder with nulls**: `1,2,#,#,3,#,#`\n- **Level order**: BFS with null placeholders\n- **BST**: preorder without nulls (BST property reconstructs)",
                "implementation_keys": "1. Serialize: preorder DFS, append val or '#' for null\n2. Deserialize: use iterator/queue, recursively build left then right\n3. Use delimiter (comma) between values",
                "common_pitfalls": "Not handling null markers correctly in deserialization. Using wrong traversal order (preorder + nulls is simplest).",
            },
        ],
    },
    {
        "topic": "Graph",
        "subtopics": [
            {
                "name": "DFS / BFS",
                "description": "Core graph traversal — DFS for exhaustive exploration, BFS for shortest path in unweighted graphs.",
                "when_to_use": "Connectivity, components, islands, flood fill, shortest path (BFS).",
                "key_signals": "number of islands, connected components, clone graph, flood fill, shortest path unweighted",
                "variants": "- **DFS iterative**: stack-based\n- **DFS recursive**: natural for trees\n- **BFS**: queue-based, guarantees shortest path\n- **Multi-source BFS**: start from all sources",
                "implementation_keys": "1. Build adjacency list: `graph = defaultdict(list)`\n2. Track visited: `visited = set()`\n3. DFS: recurse/stack on unvisited neighbors\n4. BFS: `deque`, process level by level for distance",
                "common_pitfalls": "Not marking visited before adding to queue (BFS). Stack overflow with DFS on large graphs (use iterative). Forgetting to handle disconnected components.",
            },
            {
                "name": "Topological Sort",
                "description": "Linear ordering of vertices in DAG where for every edge u→v, u comes before v.",
                "when_to_use": "Dependency ordering, course scheduling, build order.",
                "key_signals": "prerequisites, course schedule, dependency, order possible, alien dictionary",
                "variants": "- **Kahn's (BFS)**: process nodes with in-degree 0\n- **DFS-based**: reverse post-order\n- **Cycle detection**: if not all nodes processed, cycle exists",
                "implementation_keys": "1. Build adjacency list and in-degree count\n2. Queue all nodes with in-degree 0\n3. Process: decrement neighbors' in-degree, add new zeros to queue\n4. If processed count < n: cycle exists",
                "common_pitfalls": "Not detecting cycles (return empty or false). Building wrong adjacency direction. For Alien Dictionary: handling equal-length words where one is prefix of another.",
            },
            {
                "name": "Union Find",
                "description": "Disjoint Set Union — dynamically track connected components with near-O(1) operations via path compression and union by rank.",
                "when_to_use": "Dynamic connectivity, grouping, redundant edges, accounts merge.",
                "key_signals": "connected components, redundant connection, accounts merge, dynamic union",
                "variants": "- **Basic UF**: find + union\n- **Weighted UF**: track component sizes\n- **UF with rollback**: for offline queries",
                "implementation_keys": "1. `parent = list(range(n))`, `rank = [0] * n`\n2. **find(x)**: `if parent[x] != x: parent[x] = find(parent[x])` (path compression)\n3. **union(x, y)**: attach smaller rank tree under larger; if equal, increment rank\n4. Path compression + union by rank = O(α(n)) amortized",
                "common_pitfalls": "Forgetting path compression makes find O(n). In union by rank: if ranks are equal, you MUST increment the new root's rank. Not initializing parent[i] = i.",
            },
            {
                "name": "Dijkstra",
                "description": "Shortest path from single source with non-negative edge weights using priority queue.",
                "when_to_use": "Shortest/cheapest path in weighted graph with non-negative weights.",
                "key_signals": "shortest path weighted, network delay, minimum effort, cheapest flights",
                "variants": "- **Standard**: min-heap of (distance, node)\n- **Modified**: with constraints (e.g., at most k stops)\n- **0-1 BFS**: deque for 0/1 weights (faster than heap)",
                "implementation_keys": "1. `dist = {src: 0}`, `heap = [(0, src)]`\n2. Pop smallest distance node\n3. Skip if already processed (dist check)\n4. Relax neighbors: if `d + w < dist[neighbor]`, update and push",
                "common_pitfalls": "Not skipping already-processed nodes (causes O(V²) or worse). Using with negative weights (use Bellman-Ford). Pushing duplicate entries without checking.",
            },
            {
                "name": "Bellman-Ford",
                "description": "Shortest path allowing negative weights; can detect negative cycles. O(VE).",
                "when_to_use": "Shortest path with negative weights or limited number of edges (k stops).",
                "key_signals": "negative weights, cheapest flights within k stops, detect negative cycle",
                "variants": "- **Standard**: relax all edges V-1 times\n- **K-limited**: only k relaxation rounds (cheapest flights with k stops)\n- **SPFA**: queue-based optimization (average faster)",
                "implementation_keys": "1. `dist = [inf] * n`, `dist[src] = 0`\n2. Repeat V-1 times: for each edge (u,v,w): `dist[v] = min(dist[v], dist[u] + w)`\n3. For k stops: copy dist before each round to prevent cascading\n4. Negative cycle: if V-th round still relaxes, negative cycle exists",
                "common_pitfalls": "For k-stops: must copy distances before each round (otherwise paths with more than k edges are used). Not detecting negative cycles.",
            },
            {
                "name": "Floyd-Warshall",
                "description": "All-pairs shortest path in O(V³). Works with negative weights (no negative cycles).",
                "when_to_use": "All-pairs shortest distance, usually small n (n ≤ 400).",
                "key_signals": "all pairs shortest, small graph, find the city with smallest number of neighbors",
                "variants": "- **Standard**: 3 nested loops, intermediate node k\n- **Transitive closure**: check reachability",
                "implementation_keys": "1. `dist[i][j]` initialized from edges, `inf` otherwise, `0` for self\n2. For k in range(n): for i: for j: `dist[i][j] = min(dist[i][j], dist[i][k] + dist[k][j])`\n3. Order MUST be k outermost",
                "common_pitfalls": "Wrong loop order — k MUST be outermost. Not initializing `dist[i][i] = 0`. Overflow when adding `inf + weight`.",
            },
            {
                "name": "Tarjan",
                "description": "DFS-based algorithm for finding bridges, articulation points, or strongly connected components.",
                "when_to_use": "Critical connections, bridges in network, SCC decomposition.",
                "key_signals": "critical connections, bridges, articulation points, strongly connected",
                "variants": "- **Bridges**: edge (u,v) is bridge if `low[v] > disc[u]`\n- **Articulation points**: node u is AP if `low[v] >= disc[u]` (or root with 2+ children)\n- **SCC**: track stack, `low[u] == disc[u]` means SCC root",
                "implementation_keys": "1. Track `disc[u]` (discovery time) and `low[u]` (lowest reachable)\n2. DFS: `disc[u] = low[u] = timer++`\n3. For each neighbor v: if unvisited, DFS(v), then `low[u] = min(low[u], low[v])`\n4. If v already visited and not parent: `low[u] = min(low[u], disc[v])`",
                "common_pitfalls": "Confusing `disc` vs `low`. For bridges: condition is `low[v] > disc[u]` (strict). For AP: condition is `low[v] >= disc[u]` (non-strict). Root AP needs 2+ DFS children, not just 2+ neighbors.",
            },
            {
                "name": "Euler Path",
                "description": "Path that visits every EDGE exactly once. Hierholzer's algorithm builds it in O(E).",
                "when_to_use": "Reconstruct itinerary, use every edge once.",
                "key_signals": "reconstruct itinerary, use every edge, Eulerian path/circuit",
                "variants": "- **Eulerian circuit**: every vertex has even degree\n- **Eulerian path**: exactly 0 or 2 vertices with odd degree",
                "implementation_keys": "1. Check existence: in/out degree conditions\n2. Hierholzer's: DFS, add node to result AFTER all edges from it are used\n3. Reverse the result at the end\n4. For lexicographic: sort adjacency lists first",
                "common_pitfalls": "Adding node to result BEFORE vs AFTER processing all edges (must be after). Not sorting for lexicographic order. Not checking existence conditions first.",
            },
        ],
    },
    {
        "topic": "Backtracking",
        "subtopics": [
            {
                "name": "Subsets / Combinations / Permutations",
                "description": "Generate all possible selections or orderings using recursive exploration.",
                "when_to_use": "Generate all subsets, combinations of size k, or permutations.",
                "key_signals": "all subsets, all combinations, all permutations, power set, choose k from n",
                "variants": "- **Subsets**: include/exclude each element\n- **Combinations**: choose k, use start index to avoid duplicates\n- **Permutations**: try each unused element at each position\n- **With duplicates**: sort + skip same element at same level",
                "implementation_keys": "1. Subsets: `backtrack(i, path)` — add path copy, try i..n-1\n2. Combinations: same but stop when `len(path) == k`\n3. Permutations: use `used` array or swap technique\n4. Duplicates: `if i > start and nums[i] == nums[i-1]: skip`",
                "common_pitfalls": "Not copying path before adding to result (reference issues). Wrong duplicate skip condition. For permutations with duplicates: must sort and skip `nums[i] == nums[i-1] and not used[i-1]`.",
            },
            {
                "name": "Constraint Search",
                "description": "Place choices under constraints — try, validate, backtrack if invalid.",
                "when_to_use": "Placing items with constraints: N-Queens, Sudoku, word search.",
                "key_signals": "N-Queens, Sudoku, word search, valid placement, constraint satisfaction",
                "variants": "- **Grid placement**: N-Queens, Sudoku\n- **Path on grid**: word search\n- **With pruning**: eliminate impossible branches early",
                "implementation_keys": "1. Try each option at current position\n2. Check constraints before placing\n3. Place, recurse, then remove (backtrack)\n4. Prune: skip entire branches known to fail",
                "common_pitfalls": "Not checking all constraints (N-Queens: rows, cols, AND both diagonals). Not restoring state after backtracking. Not pruning enough (exponential blowup).",
            },
            {
                "name": "Backtracking + Trie",
                "description": "Combine trie with backtracking DFS to efficiently search for multiple words on a grid.",
                "when_to_use": "Word search with dictionary, boggle solver.",
                "key_signals": "word search II, find all words on board, boggle",
                "variants": "- **Trie-guided DFS**: only explore paths that exist in trie",
                "implementation_keys": "1. Build trie from word list\n2. DFS from each cell, following trie nodes\n3. If `is_end`: add word to result, remove from trie\n4. Mark cell visited during DFS, unmark after",
                "common_pitfalls": "Not removing found words from trie (causes duplicates). Not marking/unmarking visited cells. High time complexity without trie pruning.",
            },
            {
                "name": "Backtracking + Memo",
                "description": "When backtracking has overlapping subproblems, add memoization — effectively becomes top-down DP.",
                "when_to_use": "Backtracking with repeated states that can be cached.",
                "key_signals": "word break, palindrome partitioning, repeated subproblem in recursion tree",
                "variants": "- **Memoized recursion**: cache on (index, state) tuples\n- **Transition to DP**: if states are clean, convert to bottom-up",
                "implementation_keys": "1. Identify the state: what parameters uniquely define a subproblem?\n2. Cache with `@lru_cache` or dictionary\n3. State must be hashable (use tuple, not list)",
                "common_pitfalls": "State not capturing all relevant info (missing dimension). Mutable default arguments. Not recognizing when backtracking IS DP (same states revisited).",
            },
        ],
    },
    {
        "topic": "Dynamic Programming",
        "subtopics": [
            {
                "name": "1D DP",
                "description": "State depends on previous positions in a single sequence. `dp[i]` = answer for first i elements.",
                "when_to_use": "Sequential decisions: climbing stairs, house robber, word break.",
                "key_signals": "number of ways, minimum cost, can reach, optimal from sequence",
                "variants": "- **Linear scan**: `dp[i]` from `dp[i-1]`, `dp[i-2]`\n- **With hash map**: when state space is sparse\n- **Space-optimized**: keep only last 1-2 values",
                "implementation_keys": "1. Define state: what does `dp[i]` represent?\n2. Base case: `dp[0]` or `dp[0], dp[1]`\n3. Transition: `dp[i] = f(dp[i-1], dp[i-2], ...)`\n4. Answer: `dp[n]` or `dp[n-1]`",
                "common_pitfalls": "Wrong base case. Off-by-one in indexing. Not considering space optimization when only last few states needed.",
            },
            {
                "name": "2D DP",
                "description": "State depends on two indices. `dp[i][j]` = answer for subproblem defined by i and j.",
                "when_to_use": "Two sequences (LCS, edit distance), grid paths, string matching.",
                "key_signals": "longest common subsequence, edit distance, unique paths, two strings",
                "variants": "- **Two sequences**: `dp[i][j]` for `s1[0..i]` and `s2[0..j]`\n- **Grid paths**: `dp[i][j]` = ways to reach (i,j)\n- **Space-optimized**: use 1D array when dp[i][j] only depends on row i-1",
                "implementation_keys": "1. `dp[i][j]`: clearly define both dimensions\n2. Base cases: first row and first column\n3. Fill order: usually left-to-right, top-to-bottom\n4. Answer: `dp[m][n]` or `dp[m-1][n-1]`",
                "common_pitfalls": "Wrong fill order. Not initializing base cases correctly. For edit distance: confusing insert/delete/replace operations.",
            },
            {
                "name": "Knapsack",
                "description": "Choose items under a capacity/target constraint to maximize/minimize value. 0/1 knapsack or unbounded.",
                "when_to_use": "Partition into equal subsets, coin change, target sum.",
                "key_signals": "partition, subset sum, target sum, coin change, items with weight/value, capacity",
                "variants": "- **0/1 knapsack**: each item used at most once\n- **Unbounded knapsack**: items can be reused (coin change)\n- **Bounded knapsack**: limited copies of each item",
                "implementation_keys": "1. `dp[w]` = can achieve weight w (boolean) or min coins for amount w\n2. 0/1: iterate items outer, weight inner BACKWARDS\n3. Unbounded: iterate weight FORWARDS\n4. Coin change: `dp[a] = min(dp[a], dp[a-coin] + 1)`",
                "common_pitfalls": "Direction of inner loop: backwards for 0/1 (avoid reuse), forwards for unbounded. Initializing dp[0] correctly (0 for min, True for existence, 1 for count).",
            },
            {
                "name": "Interval DP",
                "description": "Solve problems on ranges [i, j] by trying all split points. `dp[i][j]` = answer for subarray i..j.",
                "when_to_use": "Burst balloons, matrix chain multiplication, palindrome partitioning, minimum cost cuts.",
                "key_signals": "burst, merge, cut, range, split point, palindrome substring, matrix chain",
                "variants": "- **Split point**: try all k in [i, j] as split/merge point\n- **Palindrome**: expand from center or check dp[i+1][j-1]\n- **Matrix chain**: minimize total multiplication cost",
                "implementation_keys": "1. `dp[i][j]` = optimal for range [i, j]\n2. Iterate by LENGTH of range (small to large)\n3. For each range, try all split points k in [i, j]\n4. `dp[i][j] = min/max over k of (dp[i][k] + dp[k+1][j] + cost)`",
                "common_pitfalls": "Wrong iteration order — must solve smaller ranges first. Off-by-one in split points. For burst balloons: virtual boundary elements at -1 and n.",
            },
            {
                "name": "Bitmask DP",
                "description": "Use bitmask to represent subset state. `dp[mask]` = answer when the set of chosen items is `mask`.",
                "when_to_use": "When n is small (≤ 20) and you need to track which items are used.",
                "key_signals": "n <= 20, visit all nodes, assign people to tasks, subset of items, TSP",
                "variants": "- **TSP-style**: `dp[mask][last]` = min cost visiting `mask` ending at `last`\n- **Assignment**: `dp[mask]` = min cost assigning first `popcount(mask)` tasks\n- **Subset enumeration**: iterate submasks with `s = (s-1) & mask`",
                "implementation_keys": "1. `dp[1 << n]` array indexed by bitmask\n2. Check bit: `mask & (1 << i)`\n3. Set bit: `mask | (1 << i)`\n4. Iterate subsets: `s = mask; while s: ...; s = (s-1) & mask`",
                "common_pitfalls": "Forgetting initial state `dp[0] = base`. Not handling empty subset in subset enumeration. Memory: 2^20 = 1M, but 2^20 * 20 = 20M entries.",
            },
            {
                "name": "Digit DP",
                "description": "Count numbers up to N satisfying digit constraints by building the number digit by digit.",
                "when_to_use": "Count numbers with property in range [0, N].",
                "key_signals": "count numbers with unique digits, number of digit one, numbers with constraint up to N",
                "variants": "- **Standard**: `dp(pos, tight, state)` with memoization\n- **Range query**: `f(R) - f(L-1)` for range [L, R]",
                "implementation_keys": "1. Convert N to string of digits\n2. Recurse: `solve(pos, tight, state)`\n3. If `tight`: max digit = N's digit at pos; else max = 9\n4. `tight_next = tight and (d == limit)`\n5. Memoize on `(pos, tight, state)`",
                "common_pitfalls": "Not handling the `tight` constraint correctly. Leading zeros need special handling. Range query: don't forget to subtract `f(L-1)`.",
            },
            {
                "name": "Graph / DAG DP",
                "description": "DP on directed acyclic graph — longest/shortest path, counting paths. Often combined with topological sort or DFS + memo.",
                "when_to_use": "Longest increasing path in matrix, longest path in DAG, number of paths.",
                "key_signals": "longest increasing path, DAG, dependency chain, number of ways in directed graph",
                "variants": "- **DFS + memo**: `dp[node]` = answer starting from node\n- **Topological order**: process in topo order, relax edges\n- **Grid as DAG**: cells with increasing values form DAG",
                "implementation_keys": "1. Model as DAG (implicit or explicit)\n2. `dp[u]` = longest path starting from u\n3. DFS with memoization: `dp[u] = 1 + max(dp[v] for v in neighbors)`\n4. Or topological sort + relax",
                "common_pitfalls": "Not recognizing grid as DAG (Longest Increasing Path). Cycles make DP invalid — must be DAG. Forgetting to memoize (exponential without it).",
            },
        ],
    },
    {
        "topic": "Greedy",
        "subtopics": [
            {
                "name": "Sorting + Greedy",
                "description": "Sort input by a key, then make locally optimal choices that lead to globally optimal solution.",
                "when_to_use": "When sorting enables provably correct local decisions.",
                "key_signals": "non-overlapping intervals, minimum arrows, queue reconstruction, scheduling",
                "variants": "- **Sort by end**: interval scheduling (maximize non-overlapping)\n- **Sort by start**: merge intervals\n- **Sort by multiple keys**: queue reconstruction",
                "implementation_keys": "1. Sort by the right key\n2. Iterate and make greedy choice\n3. Track state (last end time, current arrow position, etc.)",
                "common_pitfalls": "Sorting by wrong key (start vs end). Not proving greedy is correct (exchange argument needed). Missing edge case when intervals touch.",
            },
            {
                "name": "Heap Greedy",
                "description": "Use heap to repeatedly pick the best available option for greedy decisions.",
                "when_to_use": "When you need the current best/worst at each step: scheduling, top-k, IPO.",
                "key_signals": "meeting rooms, task scheduler, IPO, reorganize string, most frequent",
                "variants": "- **Max heap greedy**: always pick highest value available\n- **Min heap scheduling**: process earliest deadline/smallest cost\n- **Two-pass**: sort + heap for availability windows",
                "implementation_keys": "1. Sort events by one dimension\n2. Use heap to manage the other dimension\n3. For meeting rooms: min-heap of end times, push/replace",
                "common_pitfalls": "Not considering cooldown/constraints (Task Scheduler). Greedy may not work — verify with exchange argument. Heap operations are O(log n), not O(1).",
            },
            {
                "name": "Interval Greedy",
                "description": "Greedy algorithms on intervals: merging, scheduling, minimum operations.",
                "when_to_use": "Merge overlapping intervals, minimum coverage, remove overlapping.",
                "key_signals": "merge intervals, insert interval, erase overlapping, interval scheduling",
                "variants": "- **Merge**: sort by start, extend or create new\n- **Remove minimum**: sort by end, count overlaps\n- **Insert**: find position, merge with neighbors",
                "implementation_keys": "1. Sort intervals (usually by start or end)\n2. Iterate, track current interval\n3. Merge: if overlap, extend end; else start new\n4. Count non-overlapping: sort by end, track last end",
                "common_pitfalls": "Sorting by start vs end matters (different problems need different sorts). Not handling touching intervals (is [1,2],[2,3] overlapping?). Edge case: empty input.",
            },
            {
                "name": "Proof-heavy Greedy",
                "description": "Greedy where correctness is non-obvious and requires mathematical justification.",
                "when_to_use": "Jump game, gas station, candy — where local choice seems risky but is provably correct.",
                "key_signals": "jump game, gas station, candy, assign cookies, partition labels",
                "variants": "- **Forward greedy**: track reachable range (Jump Game)\n- **Circular greedy**: net gain analysis (Gas Station)\n- **Two-pass**: left-to-right then right-to-left (Candy)",
                "implementation_keys": "1. Identify the greedy invariant\n2. Prove: if greedy fails, no solution works (exchange argument)\n3. For Candy: pass left-to-right for ascending, right-to-left for descending, take max",
                "common_pitfalls": "Assuming greedy works without proof. Missing cases that require two passes. Not handling ties correctly.",
            },
        ],
    },
    {
        "topic": "Intervals",
        "subtopics": [
            {
                "name": "Merge Intervals",
                "description": "Sort intervals and merge overlapping ones. Foundation for many interval problems.",
                "when_to_use": "Merge overlapping intervals, insert new interval, find gaps.",
                "key_signals": "merge intervals, insert interval, overlapping intervals, free time",
                "variants": "- **Merge all**: sort by start, extend or append\n- **Insert and merge**: find overlap region, merge\n- **Gaps**: intervals between merged ones",
                "implementation_keys": "1. Sort by start time\n2. For each interval: if overlaps with last in result, merge (extend end)\n3. Otherwise append as new\n4. Overlap check: `current.start <= last.end`",
                "common_pitfalls": "Not taking `max(last.end, current.end)` when merging. Off-by-one with inclusive vs exclusive ends.",
            },
            {
                "name": "Sweep Line",
                "description": "Convert intervals to events (start/end), sort, and sweep through to track active count.",
                "when_to_use": "Count active intervals at any point, skyline, calendar, car pooling.",
                "key_signals": "my calendar, car pooling, skyline problem, maximum overlap, active intervals",
                "variants": "- **Event counting**: +1 at start, -1 at end, prefix sum\n- **Skyline**: track active heights with heap\n- **Coordinate compression**: discretize endpoints",
                "implementation_keys": "1. Create events: `(time, +1)` for start, `(time, -1)` for end\n2. Sort events (break ties: end before start if touching != overlapping)\n3. Sweep: running sum of events\n4. Track max active or transitions",
                "common_pitfalls": "Tie-breaking order matters (start vs end at same time). Not handling the skyline's redundant height changes. Memory for coordinate compression.",
            },
            {
                "name": "Scheduling",
                "description": "Schedule meetings or tasks using interval analysis — count rooms, find free time.",
                "when_to_use": "Meeting rooms, employee free time, job scheduling.",
                "key_signals": "meeting rooms, how many rooms needed, employee free time, overlapping meetings",
                "variants": "- **Count rooms**: sweep line or min-heap of end times\n- **Free time**: merge all intervals, find gaps\n- **Weighted scheduling**: DP + binary search",
                "implementation_keys": "1. Min-heap approach: sort by start, heap of end times\n2. If `meeting.start >= heap[0]`: reuse room (pop + push new end)\n3. Else push new end (new room needed)\n4. Heap size = rooms needed",
                "common_pitfalls": "Not sorting by start time first. For weighted scheduling: not using binary search to find compatible job. Employee free time: must merge per employee first.",
            },
        ],
    },
    {
        "topic": "Advanced Data Structures",
        "subtopics": [
            {
                "name": "Fenwick Tree",
                "description": "Binary Indexed Tree for prefix sum queries and point updates in O(log n). More space-efficient than segment tree.",
                "when_to_use": "Prefix sums with updates, count of smaller numbers, inversion count.",
                "key_signals": "count smaller after self, range sum with updates, inversion count, dynamic prefix",
                "variants": "- **Point update, range query**: standard BIT\n- **Range update, point query**: difference array + BIT\n- **2D BIT**: for 2D prefix sum with updates",
                "implementation_keys": "1. 1-indexed array of size n+1\n2. **update(i, delta)**: `while i <= n: tree[i] += delta; i += i & (-i)`\n3. **query(i)** (prefix sum): `while i > 0: sum += tree[i]; i -= i & (-i)`\n4. Range sum: `query(r) - query(l-1)`",
                "common_pitfalls": "Must be 1-indexed (0 causes infinite loop in update). `i & (-i)` extracts lowest set bit. Confusing with segment tree — BIT is simpler but less flexible (no range update + range query easily).",
            },
            {
                "name": "Segment Tree",
                "description": "A segment tree stores precomputed answers for many array intervals. Each node represents one interval, and its value is the combined answer for that interval. A query answers a larger range by stitching together a small number of stored intervals instead of scanning every element.",
                "when_to_use": "Use when values change and you still need fast range answers: range sum/min/max/gcd/count, mutable arrays, interval overlap counts, calendar booking, falling squares, and range coverage problems.",
                "key_signals": "many range queries, mutable array, point update, range update, interval aggregate, range minimum query, my calendar III, falling squares, range module",
                "variants": "- **Point update + range query**: basic segment tree; update one leaf and repair ancestors\n- **Range update + range query**: lazy propagation; store pending updates and push them down only when needed\n- **Dynamic/sparse segment tree**: huge coordinate range with few touched points\n- **Custom node data**: store min/max/sum/count/coverage instead of a single sum",
                "implementation_keys": "1. Choose the node invariant: what does one interval store?\n2. Choose the identity value and combine function.\n3. Build: create leaf values, then compute each parent from its two children.\n4. Update: change the affected leaf/range, then repair every stale ancestor.\n5. Query: consume only nodes fully inside the requested range and combine their stored answers.\n6. Lazy: for range updates, record pending changes and push before reading children.",
                "common_pitfalls": "Not defining inclusive vs half-open ranges. Using the wrong identity value for min/max/gcd. Forgetting to repair ancestors after update. In lazy propagation, reading children before pushing pending lazy values. For array-based recursive trees, allocate about 4*n nodes; for iterative trees, leaves start at n.",
            },
            {
                "name": "Ordered Set / TreeMap",
                "description": "Sorted container supporting O(log n) insert, delete, and range queries. Python: `SortedList` from `sortedcontainers`.",
                "when_to_use": "Need sorted keys dynamically, find nearest, range queries on dynamic data.",
                "key_signals": "contains duplicate III, my calendar I, count in range, nearest value",
                "variants": "- **SortedList**: for ordered elements with O(log n) operations\n- **SortedDict**: ordered key-value pairs\n- **Bisect**: for static sorted arrays",
                "implementation_keys": "1. `from sortedcontainers import SortedList`\n2. `sl.add(val)`, `sl.remove(val)`, `sl.bisect_left(val)`\n3. Range query: `sl.irange(lo, hi)`\n4. Nearest: check `bisect_left` and `bisect_right` positions",
                "common_pitfalls": "Python's built-in has no balanced BST — must use `sortedcontainers`. SortedList operations are O(log n) amortized, not worst case. Not available in all languages the same way.",
            },
            {
                "name": "LRU / LFU",
                "description": "Cache eviction data structures combining hash map with ordered structure for O(1) operations.",
                "when_to_use": "Design problems: LRU cache, LFU cache, all O(1) data structure.",
                "key_signals": "LRU cache, LFU cache, insert delete getRandom O(1), design",
                "variants": "- **LRU**: hash map + doubly linked list\n- **LFU**: hash map + frequency buckets (each with DLL)\n- **Insert/Delete/GetRandom**: hash map + array with swap-to-end delete",
                "implementation_keys": "1. LRU: `OrderedDict` — `move_to_end` on access, `popitem(last=False)` to evict\n2. Or manual: hash map of key→node, DLL for order\n3. LFU: hash map of key→(val, freq), hash map of freq→DLL\n4. Track `min_freq` for O(1) eviction",
                "common_pitfalls": "LRU: forgetting to update order on get (not just put). LFU: not updating min_freq correctly when frequency increases. O(1) requires careful pointer management.",
            },
            {
                "name": "Iterator / Generator",
                "description": "Iterator and generator patterns separate traversal logic from the code that consumes values. The iterator object holds the position in the data, and each call to `next()` advances exactly one step. Python generators use `yield` to pause execution mid-function — the local variables stay alive between calls, so you get lazy, memory-efficient traversal without building a full list.",
                "when_to_use": "Use when a problem asks you to design a class that produces values on demand: flatten a nested structure, peek at the next value without consuming it, merge multiple sorted streams, or traverse a tree one node at a time. Also useful when the full output is too large to store but you only need elements one by one.",
                "key_signals": "implement iterator, next, hasNext, peek, flatten nested list, design, yield, lazy evaluation, stream of values",
                "variants": "- **Recursive generator (`yield from`)**: flatten nested lists or trees by yielding from children — the runtime manages the call stack\n- **Peeking iterator**: wraps another iterator with a one-element cache so `peek()` returns the next value without consuming it\n- **Stack-based iterator**: replace recursion with an explicit stack when you need an iterative in-order or pre-order tree traversal as an iterator\n- **Merge iterator**: use a heap to merge `k` sorted iterators into one sorted stream",
                "implementation_keys": "1. **Generator with `yield`**: write a normal function but use `yield val` instead of appending to a list. Calling the function returns a generator object; each `next()` call runs until the next `yield`.\n2. **`yield from` for nesting**: `yield from child_generator()` delegates to another generator without an explicit loop.\n3. **Peeking iterator**: store `self._cache = None`. On `peek()`, if cache is empty, call `next()` on the underlying iterator and save it. On `next()`, return cache if present, otherwise delegate.\n4. **Stack-based BST iterator**: push all left children onto a stack. `next()` pops, returns the value, and pushes the right child's left spine.\n5. **Merge k sorted**: push `(value, iterator_index)` into a min-heap. On `next()`, pop the smallest, advance that iterator, and push its new value.",
                "common_pitfalls": "- **Consuming on peek**: `peek()` must not advance the underlying iterator — cache the value and return it on subsequent `next()` calls.\n- **`StopIteration` handling**: in Python, calling `next()` on an exhausted generator raises `StopIteration`; your `hasNext()` must handle this gracefully.\n- **Generator state**: a generator function returns a new generator each time you call it — don't confuse the function with the generator object.\n- **Stack-based iterators**: forgetting to push the right child's left spine after popping causes skipped nodes.",
            },
        ],
    },
    {
        "topic": "Math",
        "subtopics": [
            {
                "name": "Bit Manipulation",
                "description": "Use bitwise operators (AND, OR, XOR, shift) for O(1) operations on individual bits.",
                "when_to_use": "XOR for pairing/cancellation, bit counting, powers of two, encoding states.",
                "key_signals": "single number, counting bits, power of two, XOR, AND, OR, sum without +",
                "variants": "- **XOR tricks**: `a ^ a = 0`, `a ^ 0 = a` — find missing/single\n- **Bit counting**: `n & (n-1)` removes lowest set bit\n- **Bit masking**: test/set/clear specific bits",
                "implementation_keys": "1. Check bit: `num & (1 << i)`\n2. Set bit: `num | (1 << i)`\n3. Clear bit: `num & ~(1 << i)`\n4. Count bits: `while n: n &= (n-1); count += 1`\n5. Power of 2: `n > 0 and n & (n-1) == 0`",
                "common_pitfalls": "Python integers have arbitrary precision — no overflow, but right shift of negative numbers is tricky. XOR approach only works for specific problem types (odd occurrence). Operator precedence: `&` is lower than `==`.",
            },
            {
                "name": "Combinatorics",
                "description": "Counting arrangements: combinations, permutations, Catalan numbers, inclusion-exclusion.",
                "when_to_use": "Count paths, unique sequences, arrangements under constraints.",
                "key_signals": "unique paths, number of ways, count arrangements, Catalan number, permutation count",
                "variants": "- **nCr**: `math.comb(n, r)` or Pascal's triangle\n- **Catalan**: parenthesization, BST count, polygon triangulation\n- **Inclusion-exclusion**: for overlapping constraints",
                "implementation_keys": "1. `math.comb(n, r)` in Python 3.8+\n2. For modular: precompute factorials and inverse factorials\n3. Catalan: `C(n) = C(2n, n) / (n+1)`\n4. For grid paths: `C(m+n-2, m-1)`",
                "common_pitfalls": "Modular inverse needed for large values. Overflow in intermediate calculations. Not recognizing Catalan number patterns.",
            },
            {
                "name": "Number Theory",
                "description": "GCD, LCM, prime testing, modular arithmetic, Sieve of Eratosthenes.",
                "when_to_use": "Problems involving primes, divisibility, GCD/LCM, modular operations.",
                "key_signals": "GCD, prime, sieve, modular, factorial, Euler's theorem",
                "variants": "- **Euclidean GCD**: `gcd(a, b) = gcd(b, a%b)`\n- **Sieve**: O(n log log n) for all primes up to n\n- **Modular exponentiation**: fast power mod",
                "implementation_keys": "1. `math.gcd(a, b)`, `lcm = a * b // gcd(a, b)`\n2. Sieve: mark multiples starting from 2\n3. Fast power: `pow(base, exp, mod)` in Python",
                "common_pitfalls": "Integer overflow in other languages. Sieve memory for large n. Modular arithmetic: `(a - b) % m` can be negative in some languages.",
            },
            {
                "name": "Geometry",
                "description": "Computational geometry: distances, cross products, convex hull, line intersections.",
                "when_to_use": "Point/line problems, max points on line, rectangle overlap, area calculation.",
                "key_signals": "max points on a line, rectangle overlap, convex hull, distance, closest pair",
                "variants": "- **Line through points**: use slope as (dy, dx) reduced by GCD\n- **Cross product**: orientation, area, convex hull\n- **Sweep line in geometry**: for intersections",
                "implementation_keys": "1. Slope: reduce `(dy, dx)` by GCD, handle vertical lines\n2. Distance: avoid `sqrt` when possible (compare squared distances)\n3. Cross product: `(b-a) × (c-a)` for orientation\n4. Convex hull: Andrew's monotone chain O(n log n)",
                "common_pitfalls": "Floating point precision — use integer arithmetic when possible. Slope representation: must normalize (GCD + sign). Collinear points in convex hull.",
            },
        ],
    },
]


TOPIC_ORDER = [t["topic"] for t in TAXONOMY]

SUBTOPIC_TO_TOPIC: dict[str, str] = {}
for entry in TAXONOMY:
    for st in entry["subtopics"]:
        SUBTOPIC_TO_TOPIC[st["name"].lower()] = entry["topic"]

ALL_SUBTOPIC_NAMES: set[str] = {
    st["name"] for entry in TAXONOMY for st in entry["subtopics"]
}

OLD_TO_NEW: dict[str, str] = {
    "two pointers": "Two Pointers",
    "sliding window": "Sliding Window",
    "prefix array": "Prefix Sum",
    "prefix sum": "Prefix Sum",
    "subarray": "Prefix Sum",
    "binary search": "Classic Search",
    "rotation": "Two Pointers",
    "frequency": "Frequency Map",
    "rearrangement": "Sorting",
    "sorting": "Sorting",
    "binary arrays": "Prefix Sum",
    "mountain array": "Classic Search",
    "complementary array": "Two Pointers",
    "hamming distance": "Bit Manipulation",
    "distance calculation": "Geometry",
    "queries": "Prefix Sum",
    "submatrix": "Prefix Sum",
    "prime numbers": "Number Theory",
    "bfs": "DFS / BFS",
    "dfs": "DFS / BFS",
    "iterator": "Iterator / Generator",
    "generator": "Iterator / Generator",
    "iterator / generator": "Iterator / Generator",
    "dijkstra": "Dijkstra",
    "bellman-ford": "Bellman-Ford",
    "union find": "Union Find",
    "topological sort": "Topological Sort",
    "tarjan": "Tarjan",
    "euler path": "Euler Path",
    "minimum spanning tree": "DFS / BFS",
    "cycle detection": "DFS / BFS",
    "path finding": "DFS / BFS",
    "dp": "1D DP",
    "bitmask": "Bitmask DP",
    "coin change": "Knapsack",
    "optimization": "1D DP",
    "grid": "2D DP",
    "grid partition": "2D DP",
    "submatrices": "2D DP",
    "trie": "Trie",
    "edit distance": "2D DP",
    "substring": "String Sliding Window",
    "string manipulation": "String Parsing",
    "string operations": "String Parsing",
    "substitution": "String Parsing",
    "character counting": "Frequency Map",
    "binary string": "Bit Manipulation",
    "prefix": "Prefix Sum",
    "json": "String Parsing",
    "hash map": "Frequency Map",
    "palindrome": "1D DP",
    "serialization": "Serialization",
    "stack": "Normal Stack",
    "parsing": "Parsing",
    "simulation": "Normal Stack",
    "monotonic stack": "Monotonic Stack",
    "heap": "Priority Queue / Heap",
    "sweep line": "Sweep Line",
    "bit": "Fenwick Tree",
    "segment tree": "Segment Tree",
    "merge sort": "Sorting",
    "greedy": "Sorting + Greedy",
    "backtracking": "Constraint Search",
    "lexicographical order": "Subsets / Combinations / Permutations",
    "counting": "Combinatorics",
    "growth calculation": "Number Theory",
    "node deletion": "Reverse / Merge",
}
