"""cleanup: drop dead tables and questions.pattern_analysis

Revision ID: ce6a62668a73
Revises:
Create Date: 2026-06-08 00:03:48.364997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce6a62668a73'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_algorithm_template_reviews_next_review'), table_name='algorithm_template_reviews')
    op.drop_index(op.f('ix_algorithm_template_reviews_user_id'), table_name='algorithm_template_reviews')
    op.drop_table('algorithm_template_reviews')
    op.drop_index(op.f('ix_algorithm_templates_slug'), table_name='algorithm_templates')
    op.drop_index(op.f('ix_algorithm_templates_subtopic'), table_name='algorithm_templates')
    op.drop_index(op.f('ix_algorithm_templates_topic'), table_name='algorithm_templates')
    op.drop_table('algorithm_templates')
    op.drop_column('questions', 'pattern_analysis')
    op.drop_constraint(op.f('study_plan_items_template_id_fkey'), 'study_plan_items', type_='foreignkey')
    op.create_index(op.f('ix_subtopic_knowledge_slug'), 'subtopic_knowledge', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subtopic_knowledge_slug'), table_name='subtopic_knowledge')
    op.create_foreign_key(op.f('study_plan_items_template_id_fkey'), 'study_plan_items', 'algorithm_templates', ['template_id'], ['id'])
    op.add_column('questions', sa.Column('pattern_analysis', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_table('algorithm_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=160), autoincrement=False, nullable=False),
    sa.Column('topic', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('subtopic', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('when_to_use', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('signals', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('core_code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('breakdown', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('mental_model', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('variants', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('pitfalls', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('recall_tasks', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('related_question_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('algorithm_templates_pkey'))
    )
    op.create_index(op.f('ix_algorithm_templates_topic'), 'algorithm_templates', ['topic'], unique=False)
    op.create_index(op.f('ix_algorithm_templates_subtopic'), 'algorithm_templates', ['subtopic'], unique=False)
    op.create_index(op.f('ix_algorithm_templates_slug'), 'algorithm_templates', ['slug'], unique=True)
    op.create_table('algorithm_template_reviews',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('template_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quality_history', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('last_reviewed', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('next_review', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['algorithm_templates.id'], name=op.f('algorithm_template_reviews_template_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('algorithm_template_reviews_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('algorithm_template_reviews_pkey')),
    sa.UniqueConstraint('user_id', 'template_id', name=op.f('uq_template_review_user_template'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_algorithm_template_reviews_user_id'), 'algorithm_template_reviews', ['user_id'], unique=False)
    op.create_index(op.f('ix_algorithm_template_reviews_next_review'), 'algorithm_template_reviews', ['next_review'], unique=False)
    # ### end Alembic commands ###
